这节介绍数据读取

In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv('data.csv')
data

,id,AL,AZ,CA,CO,CT,FL,GA,IL,IN,...,wothers_masked_public.2,wothers_distanced_public.2,wshop_indoors.2,wrestaurant_indoors.2,wworried_catch_covid.2,hh_cmnty_cli.2,nohh_cmnty_cli.2,wearing_mask_7d.2,public_transit.2,worried_finances.2
0,0,0,0,0,0,0,1,0,0,0,...,16.187812,15.996416,63.208478,34.034397,54.787540,42.142738,35.753942,66.459333,3.549976,37.561679
1,1,0,0,0,0,0,0,0,0,0,...,35.507282,17.686027,62.887780,35.300316,49.624786,12.668497,8.902815,68.035555,8.349080,33.921755
2,2,0,0,0,0,0,0,1,0,0,...,16.988814,15.553080,66.314132,36.798828,43.224876,24.278089,19.419730,62.169775,3.609419,36.657118
3,3,0,0,0,1,0,0,0,0,0,...,33.664879,15.302950,63.439616,35.768740,46.545017,29.619471,24.495402,70.137155,4.600004,34.210536
4,4,0,0,0,0,0,0,0,0,1,...,11.893332,15.043238,55.866033,30.800247,50.350116,50.161383,43.380365,62.227135,2.188933,40.253917
5,5,0,0,0,0,0,0,0,0,0,...,26.810260,22.248963,65.539840,32.493247,51.102067,16.294294,12.139990,64.422051,14.564218,39.541182
6,6,0,0,0,0,0,0,0,1,0,...,9.814646,15.284248,66.771767,41.287243,41.566803,17.135524,11.652980,42.943643,8.801125,36.251137
7,7,0,0,0,0,0,0,0,0,0,...,8.310770,17.473428,66.905446,39.218715,40.012549,25.169346,20.431334,48.877347,5.287935,29.493133
8,8,0,0,0,0,0,0,0,0,0,...,15.554310,16.135227,65.401402,39.325008,46.766944,17.373293,11.382477,55.363492,4.223796,40.569700
9,9,0,0,0,0,0,0,0,0,0,...,61.606020,29.423811,67.945921,34.705813,45.424882,18.829529,14.813160,83.467934,4.894284,33.727603
10,10,0,0,0,0,0,0,0,0,0,...,6.246874,15.153417,67.134568,41.752754,37.953498,20.888394,15.505860,45.497850,3.621589,39.937657

In [8]:
data.to_pickle('out.pickle')

In [9]:
data2=pd.read_pickle('out.pickle')
data2

,id,AL,AZ,CA,CO,CT,FL,GA,IL,IN,...,wothers_masked_public.2,wothers_distanced_public.2,wshop_indoors.2,wrestaurant_indoors.2,wworried_catch_covid.2,hh_cmnty_cli.2,nohh_cmnty_cli.2,wearing_mask_7d.2,public_transit.2,worried_finances.2
0,0,0,0,0,0,0,1,0,0,0,...,16.187812,15.996416,63.208478,34.034397,54.787540,42.142738,35.753942,66.459333,3.549976,37.561679
1,1,0,0,0,0,0,0,0,0,0,...,35.507282,17.686027,62.887780,35.300316,49.624786,12.668497,8.902815,68.035555,8.349080,33.921755
2,2,0,0,0,0,0,0,1,0,0,...,16.988814,15.553080,66.314132,36.798828,43.224876,24.278089,19.419730,62.169775,3.609419,36.657118
3,3,0,0,0,1,0,0,0,0,0,...,33.664879,15.302950,63.439616,35.768740,46.545017,29.619471,24.495402,70.137155,4.600004,34.210536
4,4,0,0,0,0,0,0,0,0,1,...,11.893332,15.043238,55.866033,30.800247,50.350116,50.161383,43.380365,62.227135,2.188933,40.253917
5,5,0,0,0,0,0,0,0,0,0,...,26.810260,22.248963,65.539840,32.493247,51.102067,16.294294,12.139990,64.422051,14.564218,39.541182
6,6,0,0,0,0,0,0,0,1,0,...,9.814646,15.284248,66.771767,41.287243,41.566803,17.135524,11.652980,42.943643,8.801125,36.251137
7,7,0,0,0,0,0,0,0,0,0,...,8.310770,17.473428,66.905446,39.218715,40.012549,25.169346,20.431334,48.877347,5.287935,29.493133
8,8,0,0,0,0,0,0,0,0,0,...,15.554310,16.135227,65.401402,39.325008,46.766944,17.373293,11.382477,55.363492,4.223796,40.569700
9,9,0,0,0,0,0,0,0,0,0,...,61.606020,29.423811,67.945921,34.705813,45.424882,18.829529,14.813160,83.467934,4.894284,33.727603
10,10,0,0,0,0,0,0,0,0,0,...,6.246874,15.153417,67.134568,41.752754,37.953498,20.888394,15.505860,45.497850,3.621589,39.937657